"""create_initial_schema

Revision ID: db162772b805
Revises: 
Create Date: 2026-08-17 16:22:07.198127+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db162772b805'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure pgcrypto and vector support
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.execute("""
    DO $$
    BEGIN
        BEGIN
            CREATE EXTENSION IF NOT EXISTS vector;
        EXCEPTION WHEN OTHERS THEN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'vector') THEN
                CREATE DOMAIN vector AS float4[];
            END IF;
        END;
    END $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('estimated_hours IS NULL OR estimated_hours > 0', name='chk_projects_estimated_hours'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_difficulty', 'projects', ['difficulty'], unique=False)
    op.create_index(op.f('ix_projects_difficulty'), 'projects', ['difficulty'], unique=False)
    op.create_table('resources',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('estimated_minutes IS NULL OR estimated_minutes > 0', name='chk_resources_estimated_minutes'),
    sa.CheckConstraint('quality_score IS NULL OR (quality_score >= 0 AND quality_score <= 100)', name='chk_resources_quality_score'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resources_is_active', 'resources', ['is_active'], unique=False)
    op.create_index('idx_resources_type', 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_is_active'), 'resources', ['is_active'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_roles_slug', 'roles', ['slug'], unique=False)
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.create_table('skills',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('estimated_hours >= 0', name='chk_skills_estimated_hours'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_skills_category', 'skills', ['category'], unique=False)
    op.create_index('idx_skills_slug', 'skills', ['slug'], unique=False)
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assessments',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=30), nullable=True),
    sa.Column('passing_score', sa.Numeric(precision=5, scale=2), server_default='70.0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('passing_score >= 0 AND passing_score <= 100', name='chk_assessments_passing_score'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessments_skill_id', 'assessments', ['skill_id'], unique=False)
    op.create_index(op.f('ix_assessments_skill_id'), 'assessments', ['skill_id'], unique=False)
    op.create_table('learner_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_role_id', sa.UUID(), nullable=True),
    sa.Column('experience_level', sa.String(length=30), nullable=True),
    sa.Column('daily_study_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('target_duration_weeks', sa.Integer(), nullable=True),
    sa.Column('learning_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('daily_study_hours >= 0', name='chk_learner_daily_study_hours'),
    sa.CheckConstraint('target_duration_weeks > 0', name='chk_learner_target_duration_weeks'),
    sa.ForeignKeyConstraint(['target_role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_learner_profiles_target_role_id', 'learner_profiles', ['target_role_id'], unique=False)
    op.create_index('idx_learner_profiles_user_id', 'learner_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_learner_profiles_target_role_id'), 'learner_profiles', ['target_role_id'], unique=False)
    op.create_index(op.f('ix_learner_profiles_user_id'), 'learner_profiles', ['user_id'], unique=True)
    op.create_table('project_skills',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('coverage_weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.CheckConstraint('coverage_weight >= 0 AND coverage_weight <= 1', name='chk_project_skills_coverage_weight'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'skill_id')
    )
    op.create_index('idx_project_skills_project_id', 'project_skills', ['project_id'], unique=False)
    op.create_index('idx_project_skills_skill_id', 'project_skills', ['skill_id'], unique=False)
    op.create_table('resource_skills',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('coverage_weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.CheckConstraint('coverage_weight >= 0 AND coverage_weight <= 1', name='chk_resource_skills_coverage_weight'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'skill_id')
    )
    op.create_index('idx_resource_skills_resource_id', 'resource_skills', ['resource_id'], unique=False)
    op.create_index('idx_resource_skills_skill_id', 'resource_skills', ['skill_id'], unique=False)
    op.create_table('role_skills',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('required_proficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('importance', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('importance >= 0 AND importance <= 1', name='chk_role_skills_importance'),
    sa.CheckConstraint('required_proficiency >= 0 AND required_proficiency <= 100', name='chk_role_skills_proficiency'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'skill_id')
    )
    op.create_index('idx_role_skills_role_id', 'role_skills', ['role_id'], unique=False)
    op.create_index('idx_role_skills_skill_id', 'role_skills', ['skill_id'], unique=False)
    op.create_table('skill_prerequisites',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_skill_id', sa.UUID(), nullable=False),
    sa.Column('strength', sa.Numeric(precision=5, scale=4), server_default='1.0', nullable=False),
    sa.CheckConstraint('skill_id != prerequisite_skill_id', name='chk_skill_prerequisites_no_self_ref'),
    sa.CheckConstraint('strength >= 0 AND strength <= 1', name='chk_skill_prerequisites_strength'),
    sa.ForeignKeyConstraint(['prerequisite_skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id', 'prerequisite_skill_id')
    )
    op.create_index('idx_skill_prereq_prereq_id', 'skill_prerequisites', ['prerequisite_skill_id'], unique=False)
    op.create_index('idx_skill_prereq_skill_id', 'skill_prerequisites', ['skill_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=40), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Numeric(precision=8, scale=2), server_default='1.0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('points > 0', name='chk_assessment_questions_points'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessment_questions_assessment_id', 'assessment_questions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skill_mastery', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name='chk_assessment_results_attempt_number'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='chk_assessment_results_score'),
    sa.CheckConstraint('skill_mastery >= 0 AND skill_mastery <= 100', name='chk_assessment_results_mastery'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'learner_id', 'attempt_number', name='uq_assessment_results_attempt')
    )
    op.create_index('idx_assessment_results_assessment_id', 'assessment_results', ['assessment_id'], unique=False)
    op.create_index('idx_assessment_results_learner_id', 'assessment_results', ['learner_id'], unique=False)
    op.create_index(op.f('ix_assessment_results_assessment_id'), 'assessment_results', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_results_learner_id'), 'assessment_results', ['learner_id'], unique=False)
    op.create_table('conversations',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_learner_id', 'conversations', ['learner_id'], unique=False)
    op.create_index(op.f('ix_conversations_learner_id'), 'conversations', ['learner_id'], unique=False)
    op.create_table('feedback',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='chk_feedback_rating'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_learner_id', 'feedback', ['learner_id'], unique=False)
    op.create_index('idx_feedback_resource_id', 'feedback', ['resource_id'], unique=False)
    op.create_index(op.f('ix_feedback_learner_id'), 'feedback', ['learner_id'], unique=False)
    op.create_index(op.f('ix_feedback_resource_id'), 'feedback', ['resource_id'], unique=False)
    op.create_table('learner_skills',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='chk_learner_skills_confidence'),
    sa.CheckConstraint('proficiency >= 0 AND proficiency <= 100', name='chk_learner_skills_proficiency'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_id', 'skill_id')
    )
    op.create_index('idx_learner_skills_learner_id', 'learner_skills', ['learner_id'], unique=False)
    op.create_index('idx_learner_skills_skill_id', 'learner_skills', ['skill_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 1', name='chk_recommendations_score'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendations_learner_id', 'recommendations', ['learner_id'], unique=False)
    op.create_index('idx_recommendations_resource_id', 'recommendations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_recommendations_learner_id'), 'recommendations', ['learner_id'], unique=False)
    op.create_index(op.f('ix_recommendations_resource_id'), 'recommendations', ['resource_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('target_role_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('estimated_weeks', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('estimated_weeks IS NULL OR estimated_weeks > 0', name='chk_roadmaps_estimated_weeks'),
    sa.CheckConstraint('version >= 1', name='chk_roadmaps_version'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'version', name='uq_roadmaps_learner_version')
    )
    op.create_index('idx_roadmaps_learner_id', 'roadmaps', ['learner_id'], unique=False)
    op.create_index('idx_roadmaps_status', 'roadmaps', ['status'], unique=False)
    op.create_index('idx_roadmaps_target_role_id', 'roadmaps', ['target_role_id'], unique=False)
    op.create_index(op.f('ix_roadmaps_learner_id'), 'roadmaps', ['learner_id'], unique=False)
    op.create_index(op.f('ix_roadmaps_status'), 'roadmaps', ['status'], unique=False)
    op.create_index(op.f('ix_roadmaps_target_role_id'), 'roadmaps', ['target_role_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='chk_conversation_messages_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_messages_conv_id', 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('roadmap_items',
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='LOCKED', nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), server_default='0.0', nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('locked_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name='chk_roadmap_items_progress'),
    sa.CheckConstraint('sequence >= 1', name='chk_roadmap_items_sequence'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'sequence', name='uq_roadmap_items_sequence')
    )
    op.create_index('idx_roadmap_items_roadmap_id', 'roadmap_items', ['roadmap_id'], unique=False)
    op.create_index('idx_roadmap_items_sequence', 'roadmap_items', ['sequence'], unique=False)
    op.create_index('idx_roadmap_items_status', 'roadmap_items', ['status'], unique=False)
    op.create_index(op.f('ix_roadmap_items_roadmap_id'), 'roadmap_items', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_items_status'), 'roadmap_items', ['status'], unique=False)
    op.create_table('roadmap_versions',
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('version >= 1', name='chk_roadmap_versions_version'),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roadmap_id', 'version', name='uq_roadmap_versions_version')
    )
    op.create_index('idx_roadmap_versions_roadmap_id', 'roadmap_versions', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_versions_roadmap_id'), 'roadmap_versions', ['roadmap_id'], unique=False)
    op.create_table('progress',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('roadmap_item_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), server_default='0.0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('percentage >= 0 AND percentage <= 100', name='chk_progress_percentage'),
    sa.CheckConstraint('time_spent_minutes >= 0', name='chk_progress_time_spent'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_item_id'], ['roadmap_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_progress_learner_id', 'progress', ['learner_id'], unique=False)
    op.create_index('idx_progress_roadmap_item_id', 'progress', ['roadmap_item_id'], unique=False)
    op.create_index(op.f('ix_progress_learner_id'), 'progress', ['learner_id'], unique=False)
    op.create_index(op.f('ix_progress_roadmap_item_id'), 'progress', ['roadmap_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_roadmap_item_id'), table_name='progress')
    op.drop_index(op.f('ix_progress_learner_id'), table_name='progress')
    op.drop_index('idx_progress_roadmap_item_id', table_name='progress')
    op.drop_index('idx_progress_learner_id', table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_roadmap_versions_roadmap_id'), table_name='roadmap_versions')
    op.drop_index('idx_roadmap_versions_roadmap_id', table_name='roadmap_versions')
    op.drop_table('roadmap_versions')
    op.drop_index(op.f('ix_roadmap_items_status'), table_name='roadmap_items')
    op.drop_index(op.f('ix_roadmap_items_roadmap_id'), table_name='roadmap_items')
    op.drop_index('idx_roadmap_items_status', table_name='roadmap_items')
    op.drop_index('idx_roadmap_items_sequence', table_name='roadmap_items')
    op.drop_index('idx_roadmap_items_roadmap_id', table_name='roadmap_items')
    op.drop_table('roadmap_items')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_index('idx_conversation_messages_conv_id', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_roadmaps_target_role_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_status'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_learner_id'), table_name='roadmaps')
    op.drop_index('idx_roadmaps_target_role_id', table_name='roadmaps')
    op.drop_index('idx_roadmaps_status', table_name='roadmaps')
    op.drop_index('idx_roadmaps_learner_id', table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_recommendations_resource_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_learner_id'), table_name='recommendations')
    op.drop_index('idx_recommendations_resource_id', table_name='recommendations')
    op.drop_index('idx_recommendations_learner_id', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_learner_skills_skill_id', table_name='learner_skills')
    op.drop_index('idx_learner_skills_learner_id', table_name='learner_skills')
    op.drop_table('learner_skills')
    op.drop_index(op.f('ix_feedback_resource_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_learner_id'), table_name='feedback')
    op.drop_index('idx_feedback_resource_id', table_name='feedback')
    op.drop_index('idx_feedback_learner_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_conversations_learner_id'), table_name='conversations')
    op.drop_index('idx_conversations_learner_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_assessment_results_learner_id'), table_name='assessment_results')
    op.drop_index(op.f('ix_assessment_results_assessment_id'), table_name='assessment_results')
    op.drop_index('idx_assessment_results_learner_id', table_name='assessment_results')
    op.drop_index('idx_assessment_results_assessment_id', table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_index('idx_assessment_questions_assessment_id', table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index('idx_skill_prereq_skill_id', table_name='skill_prerequisites')
    op.drop_index('idx_skill_prereq_prereq_id', table_name='skill_prerequisites')
    op.drop_table('skill_prerequisites')
    op.drop_index('idx_role_skills_skill_id', table_name='role_skills')
    op.drop_index('idx_role_skills_role_id', table_name='role_skills')
    op.drop_table('role_skills')
    op.drop_index('idx_resource_skills_skill_id', table_name='resource_skills')
    op.drop_index('idx_resource_skills_resource_id', table_name='resource_skills')
    op.drop_table('resource_skills')
    op.drop_index('idx_project_skills_skill_id', table_name='project_skills')
    op.drop_index('idx_project_skills_project_id', table_name='project_skills')
    op.drop_table('project_skills')
    op.drop_index(op.f('ix_learner_profiles_user_id'), table_name='learner_profiles')
    op.drop_index(op.f('ix_learner_profiles_target_role_id'), table_name='learner_profiles')
    op.drop_index('idx_learner_profiles_user_id', table_name='learner_profiles')
    op.drop_index('idx_learner_profiles_target_role_id', table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_index(op.f('ix_assessments_skill_id'), table_name='assessments')
    op.drop_index('idx_assessments_skill_id', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_index('idx_skills_slug', table_name='skills')
    op.drop_index('idx_skills_category', table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_index('idx_roles_slug', table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_active'), table_name='resources')
    op.drop_index('idx_resources_type', table_name='resources')
    op.drop_index('idx_resources_is_active', table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_projects_difficulty'), table_name='projects')
    op.drop_index('idx_projects_difficulty', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
